export const CARD_EDITOR_SHORTCUTS_EDIT = [
  { key: '1 / 2 / 3',      descKey: 'shortcut.tabSelectCard' },
  { key: 'J / K',          descKey: 'shortcut.focusNextPrev' },
  { key: 'E',              descKey: 'shortcut.editFocusedItem' },
  { key: 'R',              descKey: 'shortcut.runFocused' },
  { key: 'Delete',         descKey: 'shortcut.delete' },
  { key: 'A',              descKey: 'shortcut.toggleAddMenu' },
  { key: 'Return',         descKey: 'shortcut.addBlock' },
  { key: 'U / D', descKey: 'shortcut.scrollUpDown' },
  { key: '⇧U / ⇧D',  descKey: 'shortcut.scrollTopBottom' },
  { key: 'T',              descKey: 'shortcut.scrollToTags' },
  { key: 'M',              descKey: 'shortcut.cycleMode' },
  { key: 'C',              descKey: 'shortcut.duplicateCard' },
  { key: '⇧E',             descKey: 'shortcut.archiveToggle' },
  { key: 'S',              descKey: 'shortcut.save' },
  { key: 'X',              descKey: 'shortcut.close' },
  { key: '?',              descKey: 'shortcut.showShortcuts' },
  { key: 'ESC',            descKey: 'shortcut.esc' },
];

export const CARD_EDITOR_SHORTCUTS_SORT = [
  { key: 'J / K', descKey: 'shortcut.focusNextPrev' },
  { key: 'U / D', descKey: 'shortcut.moveFocused' },
  { key: 'M',     descKey: 'shortcut.cycleMode' },
  { key: 'Delete', descKey: 'shortcut.delete' },
  { key: 'C',     descKey: 'shortcut.duplicateCard' },
  { key: '⇧E',    descKey: 'shortcut.archiveToggle' },
  { key: 'S',     descKey: 'shortcut.save' },
  { key: 'X',     descKey: 'shortcut.close' },
  { key: '?',     descKey: 'shortcut.showShortcuts' },
  { key: 'ESC',   descKey: 'shortcut.esc' },
];

export const CARD_EDITOR_SHORTCUTS_PREVIEW = [
  { key: '1 / 2 / 3',      descKey: 'shortcut.tabSelectCard' },
  { key: 'U / D', descKey: 'shortcut.scrollUpDown' },
  { key: '⇧U / ⇧D',  descKey: 'shortcut.scrollTopBottom' },
  { key: 'M',              descKey: 'shortcut.cycleMode' },
  { key: 'C',              descKey: 'shortcut.duplicateCard' },
  { key: 'Delete',         descKey: 'shortcut.deleteCard' },
  { key: 'S',              descKey: 'shortcut.save' },
  { key: 'X',              descKey: 'shortcut.close' },
  { key: '?',              descKey: 'shortcut.showShortcuts' },
  { key: 'ESC',            descKey: 'shortcut.esc' },
];
